---
- name: install apache
  yum:
    name: httpd
    state: present

- name: copy index.html to default docroot
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: start and enable apache service
  service:
    name: httpd
    state: started
    enabled: yes

