---
- name: create tomcat user
  user:
    name: "{{ appuser }}"
    state: present

- name: Download foo.conf
  get_url:
    url: "{{ tomcat_download_url }}"
    dest: "/opt/{{ tomcat_dir }}.tar.gz"

- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: "/opt/{{ tomcat_dir }}.tar.gz"
    dest: /opt
    remote_src: yes

- name: changing ownership
  file:
    path:  "/opt/{{ tomcat_dir }}"
    state: directory
    recurse: yes
    owner: "{{ appuser }}"
    group: "{{ appuser }}"

- name: copy manager context.xml
  template:
    src: manager_context.xml.j2
    dest:" /opt/{{ tomcat_dir }}"/webapps/manager/META-INF/context.xml
    owner: "{{ appuser }}"
    group: "{{ appuser }}"
  notify: restart tomcat

- name: copy tomcat user file
  template:
    src: tomcat-users.xml.j2
    dest: "/opt/{{ tomcat_dir }}"/conf/tomcat-users.xml
    owner: "{{ appuser }}"
    group: "{{ appuser }}"
  notify: restart tomcat

- name: copy tomcat service file
  template:
    src: tomcat.service
    dest: /etc/systemd/system/tomcat.service
    owner: "{{ rootuser }}"
    group: "{{ rootuser }}"
    mode: 0755
  notify: restart tomcat

- name: start and enable tomcat service
  service:
    name: "{{ appuser }}"
    state: started
    enabled: yes

